name: Update Temp Data to Google Drive

on:
  schedule:
    - cron: '0 13 1 1 *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y gdal-bin libgdal-dev

      - name: Download existing CSV from Google Drive
        env:
          GDRIVE_FILE_ID: 1xOOdlihu-G1GTcWOccdglGqF-t4_CXnd
        run: |
          echo "Downloading weatherdata.csv from Google Drive..."
          gdown https://drive.google.com/uc?id=$GDRIVE_FILE_ID -O temperature-anomaly.csv
          
      - name: Set timezone to Bangkok
        run: sudo timedatectl set-timezone Asia/Bangkok

      - name: Run tmd data scraper
        run: python Weather_data.py

      - name: Upload updated CSV to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./temperature-anomaly.csv
          name: temperature-anomaly.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false
